### ISSUE TITLE
Windows/Mac OS functionality?

### ISSUE THREAD

**Issue by vemuribv** [BeelGroup/Auto-Surprise#18]
Hello! I'm very interested in using this package for surprise algorithm selection but not sure if it's working properly for me. I see in Setup it's mentioned that the package requires installation on linux. Is the package not functional on Windows or Mac in that case?

I tried running the ml-100k usage example on my Windows 10 machine but I don't think the output I got was correct (best_model: svd, best_params: NoneType object of builtins module, best_score: 100). Or if this is the intended output could you advise on how to interpret it?
![Annotation 2020-06-18 151226](https://user-images.githubusercontent.com/59896417/85062236-1ed8bf80-b176-11ea-9e7e-cae7261e13b8.png)

Thank you

**Comment by vemuribv** [comment]
I was able to try it on a Mac and the ml-100k example is actually working fine now for me. Still curious about if usage on Windows is possible. Thanks!

**Comment by thededlier** [comment]
Hi @vemuribv . Auto-Surprise relies on the signal module to be able to put a time limit on tasks. `signal.SIGALRM` does not work on windows. I might be changing this implementation to support Windows but not in the near future. An alternative for now is to use WSL.

Also thanks for verifying that its working on Mac 😄, I hadn't tested that yet.

**Comment by thededlier** [comment]
Regarding the output of best score being a 100, that is a placeholder value which generally means it was an exception. I'll make that more clear in a later release.

**Comment by vemuribv** [comment]
Thanks for the quick response! Just one more question, even though I'm getting the following output on Mac (which made me believe the package is working):

![Screen Shot 2020-06-20 at 3 06 32 PM](https://user-images.githubusercontent.com/59896417/85209652-a275e600-b307-11ea-953a-0ef317ceb2d8.png)

I'm also getting these errors when I run the ml-100k example:
![Screen Shot 2020-06-20 at 3 07 14 PM](https://user-images.githubusercontent.com/59896417/85209669-bb7e9700-b307-11ea-819f-c59cf7002cc4.png)
Is there a way for me to avoid these errors? Do I need to adjust cpu_time_limit or max_evals? Would increasing cpu_time_limit to something arbitrarily large (like 1e10) be a way to get around this?

I saw in limits.py the signal.SIGALRM you mentioned but I'm not clear on what causes it to throw that error.

**Comment by thededlier** [comment]
There was an issue with the `max_evals` argument and the `cpu_time_limit` argument being swapped. Its fixed now in the latest release. Would recommend you update to it. That should solve the problem.
