### ISSUE TITLE
available parameters ?

### ISSUE THREAD

**Issue by sateesh1984** [BeelGroup/Auto-Surprise#34]
when it comes to KNN based algos, what similarity options it uses...Also, does it have user_baed parameter as usual surprise library does at sim_options?

**Comment by thededlier** [comment]
It has all the available parameters that KNN has in Surprise. You can see the actual definition of the similarity options space below

https://github.com/BeelGroup/Auto-Surprise/blob/11a2569a08fb1849e9c548c6d030e0bb47570f88/auto_surprise/algorithms/spaces.py#L45-L50
